on: workflow_dispatch
name: Slack Notification Demo
jobs:
  slack:
    runs-on: ubuntu-latest
    
    steps:
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"C037VU6K8EM\",\"text\":\"Hello world\"}'
