name: Newman Run
on: workflow_dispatch

jobs:
  newman-test-api:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it    
    - name: Checkout Repository
      uses: actions/checkout@master
      
    # Install Node on the runner
    - name: Install Node
      uses: actions/setup-node@v1
      with: 
        node-version: '17.x'
          
    # Install the newman command line utility and also install the html extra reporter
    - name: Install newman
      run: |
       npm install -g newman
       npm install -g newman-reporter-htmlextra
       npm install newman-reporter-slack
    
    # give permission file
    #- name: set permission newman
    #  run: |
    #   chmod 744 Newman-to-Slack.sh
 
    #Run POSTMAN collection
    - name: run newman and send notify to slack
      run: |
        newman run ./tests/payment-backend-collection.json -r cli,slack --reporter-slack-channel 'test-auto-payment' --reporter-slack-webhook-url 'https://hooks.slack.com/services/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'
