name: Newman Run
on: workflow_dispatch
  #push:
    #branches:
      #- master
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it    
    - name: Checkout Repository
      uses: actions/checkout@master
      
    # Install Node on the runner
    - name: Install Node
      uses: actions/setup-node@v1
      with: 
        node-version: '17.x'
          
    # Install the newman command line utility and also install the html extra reporter
    - name: Install newman
      run: |
       npm install -g newman
       npm install -g newman-reporter-htmlextra
    
    # Make directory to upload the test results
    - name: Make Directory for results
      run: |
        mkdir -p testResults
 
   # Run POSTMAN collection and output the file as html
    #- name: Run POSTMAN collection
    #  run: |    
    #    newman run ./tests/payment-backend-collection.json -e ./tests/payment-backend-collection-env.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html
   
   # Push   
    - name: Commit built assets
      run: |
        newman run ./tests/payment-backend-collection.json
        git config --local user.email "mattanapornp@rabbit.co.th"
        git config --local user.name "GitHub Action"
        git checkout -B master
        git add .
        git commit -m "test add result"
        git push -f origin master    
        
    # Upload test results
    - name: Output the run Details
      uses: actions/upload-artifact@v2
      with: 
       name: RunReports
       path: testResults
       
       
