name: Newman Run
on: workflow_dispatch
  #push:
    #branches:
      #- master
jobs:
  newman-test-api:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it    
    - name: Checkout Repository
      uses: actions/checkout@master
      
    # Install Node on the runner
    - name: Install Node
      uses: actions/setup-node@v1
      with: 
        node-version: '17.x'
          
    # Install the newman command line utility and also install the html extra reporter
    - name: Install newman
      run: |
       npm install -g newman
       npm install -g newman-reporter-htmlextra
    
    # Make directory to upload the test results
    - name: Make Directory for results
      run: |
        mkdir -p testResults
 
    #Run POSTMAN collection and output the file as html
    - name: Run POSTMAN collection
      run: |    
        newman run ./tests/payment-backend-collection.json -e ./tests/payment-backend-collection-env.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html
        
    # Upload test results
    - name: Output the run Details
      uses: actions/upload-artifact@v2
      with: 
       name: RunReports
       path: testResults

    # Send notify to slack channel
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{"channel":"C037VU6K8EM","text":"I hope the tour went well, Mr. Wonka."}'
        #args: '{\"channel\":\"C037VU6K8EM\",\"Payment backend collection\":\"Passed\",\"See test result\":\"https%3A%2F%2Fgithub.com%2Fmattanapornp%2Ftest-rabbit%2Factions%2Fworkflows%2Fmain.yml\"}'
